# ***Using Logistic Regression To Predict Absenteeism***

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv('1.1 Absenteeism_preprocessed.csv.csv')

In [3]:
data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [4]:
data['Absenteeism Time in Hours'].value_counts()

8      195
2      149
3      106
1       87
4       57
0       39
16      18
24      15
40       7
5        7
32       6
64       3
112      2
56       2
80       2
120      2
48       1
7        1
104      1
Name: Absenteeism Time in Hours, dtype: int64

In [5]:
data['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data['Absenteeism Time in Hours']>3, 1, 0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [9]:
data['Excessive Absentism'] = targets

In [10]:
data.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absentism  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0

In [11]:
data['Excessive Absentism'].value_counts()

0    381
1    319
Name: Excessive Absentism, dtype: int64

In [12]:
data_preprocessed = data.drop(['Absenteeism Time in Hours'], axis=1)
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absentism  
0               30          0         2    1                    1  
1               31          0         1    0                    0  
2               31          0         0    0                    0  
3               24          0         2    0                    1  
4               30          0         2    1                    0

## Feature Scaling(Excluding Dummy Vaiables)

In [13]:
data_preprocessed.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet', 'Excessive Absentism'], dtype=object)

In [14]:
columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

In [15]:
pd.options.display.max_rows = None
pd.options.display.max_columns = None

data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
5           0         0         0         1           10                2   
6           0         0         0         1            7                4   
7           0         0         0         1            7                4   
8           0         0         1         0            6                6   
9           0         0         0         1            7                0   
10          1         0         0         0            7                0   
11          1         0         0         0            7                1   
12          1         0         0         0            7                2   
13          1         0         0         0            7                2   
14          0         0         0         1            7                2   
15          1         0         0         0            7                4   
16          0         0         0         1            7                4   
17          0         0         1         0            7                0   
18          1         0         0         0            7                3   
19          0         0         0         1            5                4   
20          1         0         0         0           12                1   
21          1         0         0         0            3                6   
22          1         0         0         0           10                3   
23          0         0         0         1            8                4   
24          0         0         1         0            8                0   
25          0         0         0         1            8                0   
26          0         0         0         1            4                2   
27          0         0         0         1           12                1   
28          0         0         1         0            8                2   
29          0         0         0         1            8                4   
30          0         0         1         0            8                0   
31          0         0         1         0            8                3   
32          0         0         0         1            8                3   
33          0         0         1         0            8                0   
34          0         0         0         1            8                0   
35          0         0         0         1            8                0   
36          0         0         0         1            4                2   
37          1         0         0         0            8                3   
38          0         0         0         1            8                4   
39          0         0         0         1            8                4   
40          0         0         0         1            1                4   
41          0         0         0         1            7                3   
42          0         0         0         1            1                4   
43          0         0         1         0            8                6   
44          0         0         0         1            9                2   
45          0         0         0         1            9                6   
46          0         0         0         1            9                0   
47          0         0         0         1            9                3   
48          0         0         0         1            4                3   
49          1         0         0         0            9                0   
50          0         0         0         0            9                0   
5

In [16]:
sc = StandardScaler()
data_preprocessed[columns_to_scale] = sc.fit_transform(data_preprocessed[columns_to_scale])

C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [17]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.030796        -0.800950   
1           0         0         0         0     0.030796        -0.800950   
2           0         0         0         1     0.030796        -0.232900   
3           1         0         0         0     0.030796         0.335149   
4           0         0         0         1     0.030796         0.335149   
5           0         0         0         1     0.929019        -0.232900   
6           0         0         0         1     0.030796         0.903199   
7           0         0         0         1     0.030796         0.903199   
8           0         0         1         0    -0.268611         2.039298   
9           0         0         0         1     0.030796        -1.368999   
10          1         0         0         0     0.030796        -1.368999   
11          1         0         0         0     0.030796        -0.800950   
12          1         0         0         0     0.030796        -0.232900   
13          1         0         0         0     0.030796        -0.232900   
14          0         0         0         1     0.030796        -0.232900   
15          1         0         0         0     0.030796         0.903199   
16          0         0         0         1     0.030796         0.903199   
17          0         0         1         0     0.030796        -1.368999   
18          1         0         0         0     0.030796         0.335149   
19          0         0         0         1    -0.568019         0.903199   
20          1         0         0         0     1.527833        -0.800950   
21          1         0         0         0    -1.166834         2.039298   
22          1         0         0         0     0.929019         0.335149   
23          0         0         0         1     0.330204         0.903199   
24          0         0         1         0     0.330204        -1.368999   
25          0         0         0         1     0.330204        -1.368999   
26          0         0         0         1    -0.867426        -0.232900   
27          0         0         0         1     1.527833        -0.800950   
28          0         0         1         0     0.330204        -0.232900   
29          0         0         0         1     0.330204         0.903199   
30          0         0         1         0     0.330204        -1.368999   
31          0         0         1         0     0.330204         0.335149   
32          0         0         0         1     0.330204         0.335149   
33          0         0         1         0     0.330204        -1.368999   
34          0         0         0         1     0.330204        -1.368999   
35          0         0         0         1     0.330204        -1.368999   
36          0         0         0         1    -0.867426        -0.232900   
37          1         0         0         0     0.330204         0.335149   
38          0         0         0         1     0.330204         0.903199   
39          0         0         0         1     0.330204         0.903199   
40          0         0         0         1    -1.765648         0.903199   
41          0         0         0         1     0.030796         0.335149   
42          0         0         0         1    -1.765648         0.903199   
43          0         0         1         0     0.330204         2.039298   
44          0         0         0         1     0.629611        -0.232900   
45          0         0         0         1     0.629611         2.039298   
46          0         0         0         1     0.629611        -1.368999   
47          0         0         0         1     0.629611         0.335149   
48          0         0         0         1    -0.867426         0.335149   
49          1         0         0         0     0.629611        -1.368999   
50          0         0         0         0     0.629611        -1.368999   
5

## Selecting Dependent And Independent Variables

In [18]:

X = data_preprocessed.iloc[:, :-1].values
Y = data_preprocessed.iloc[:, 14].values

## For Printing Whole Array In NumPy

In [19]:
np.set_printoptions(threshold=np.nan)

In [20]:
X

array([[ 0.        ,  0.        ,  0.        ,  1.        ,  0.03079619,
        -0.80094984,  1.00584437,  0.41281584, -0.53606239, -0.80633129,
         0.76743118,  0.        ,  0.88046927,  0.26848661],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.03079619,
        -0.80094984, -1.57468098, -1.1418824 ,  2.13080317, -0.80633129,
         1.00263338,  0.        , -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.03079619,
        -0.23290031, -0.6541427 ,  1.42674947,  0.24830984, -0.80633129,
         1.00263338,  0.        , -0.91902997, -0.58968976],
       [ 1.        ,  0.        ,  0.        ,  0.        ,  0.03079619,
         0.33514923,  0.85493646, -1.68264701,  0.40518428, -0.80633129,
        -0.64378202,  0.        ,  0.88046927, -0.58968976],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.03079619,
         0.33514923,  1.00584437,  0.41281584, -0.53606239, -0.80633129,
         0.76743118,  0.  

## Splitting into test and train data

In [21]:
X_train, X_test, Y_train, Y_test =train_test_split(X, Y, test_size=0.2, random_state=0)

In [22]:
X_test

array([[ 0.        ,  0.        ,  0.        ,  1.        ,  0.92901852,
         0.33514923, -1.57468098, -1.1418824 ,  2.13080317, -0.16964817,
         1.00263338,  0.        , -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        ,  1.        , -1.46624102,
        -0.23290031, -0.6541427 , -0.26313992, -1.00668572, -0.18885143,
        -1.81979303,  1.        , -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        ,  1.        , -1.76564846,
         0.90319876, -0.57868874,  0.81838929, -1.47730906, -0.75827313,
        -1.34938863,  0.        , -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.33020364,
         0.33514923,  1.03602595,  0.07483796,  0.56205873, -0.5502128 ,
        -0.40857982,  0.        , -0.01928035,  0.26848661],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.03079619,
        -0.23290031, -0.6541427 ,  1.42674947,  0.24830984, -0.80633129,
         1.00263338,  0.  

## Fitting Logistic Regression

In [23]:
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, Y_train)

C:\Users\ankit\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [24]:
classifier.score(X_train, Y_train)

0.7625

## Predicting With Test Set

In [25]:
Y_Pred = classifier.predict(X_test)

## Confusin Matrix

In [26]:
cm = confusion_matrix(Y_test, Y_Pred)
cm

array([[57, 15],
       [19, 49]], dtype=int64)

In [27]:
accuracy_score(Y_test, Y_Pred)

0.7571428571428571

## Finding Intercept And Coefficients

In [28]:
classifier.intercept_

array([-1.4911198])

In [29]:
classifier.coef_

array([[ 2.51219149,  0.39426425,  2.96624754,  0.66194842,  0.00678983,
        -0.10678799,  0.60797506,  0.0341006 , -0.16141509,  0.02764361,
         0.20772946,  0.1160823 ,  0.47524168, -0.29905387]])

## Creating Summary Table

In [30]:
X1 = data_preprocessed.iloc[:, :-1]

In [31]:
X1.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [32]:
feature_name = X1.columns.values

In [33]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(classifier.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', classifier.intercept_[0]]

In [34]:
summary_table = summary_table.sort_index()

In [35]:
summary_table

Feature name  Coefficients
0                 Intercept     -1.491120
1                  Reason_1      2.512191
2                  Reason_2      0.394264
3                  Reason_3      2.966248
4                  Reason_4      0.661948
5               Month Value      0.006790
6           Day of the Week     -0.106788
7    Transportation Expense      0.607975
8          Distance to Work      0.034101
9                       Age     -0.161415
10  Daily Work Load Average      0.027644
11          Body Mass Index      0.207729
12                Education      0.116082
13                 Children      0.475242
14                      Pet     -0.299054

In [36]:
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficients)
summary_table
summary_table.sort_values('Odds_Ratio', ascending=False)

Feature name  Coefficients  Odds_Ratio
3                  Reason_3      2.966248   19.418914
1                  Reason_1      2.512191   12.331926
4                  Reason_4      0.661948    1.938566
7    Transportation Expense      0.607975    1.836708
13                 Children      0.475242    1.608403
2                  Reason_2      0.394264    1.483292
11          Body Mass Index      0.207729    1.230880
12                Education      0.116082    1.123088
8          Distance to Work      0.034101    1.034689
10  Daily Work Load Average      0.027644    1.028029
5               Month Value      0.006790    1.006813
6           Day of the Week     -0.106788    0.898716
9                       Age     -0.161415    0.850939
14                      Pet     -0.299054    0.741519
0                 Intercept     -1.491120    0.225120

In [43]:
summary_table

Feature name  Coefficients  Odds_Ratio
0                 Intercept     -1.491120    0.225120
1                  Reason_1      2.512191   12.331926
2                  Reason_2      0.394264    1.483292
3                  Reason_3      2.966248   19.418914
4                  Reason_4      0.661948    1.938566
5               Month Value      0.006790    1.006813
6           Day of the Week     -0.106788    0.898716
7    Transportation Expense      0.607975    1.836708
8          Distance to Work      0.034101    1.034689
9                       Age     -0.161415    0.850939
10  Daily Work Load Average      0.027644    1.028029
11          Body Mass Index      0.207729    1.230880
12                Education      0.116082    1.123088
13                 Children      0.475242    1.608403
14                      Pet     -0.299054    0.741519

## Saving Model

In [39]:
import pickle
with open('model', 'wb') as file:
    pickle.dump(classifier, file)

## Loading Model

In [41]:
with open('model', 'rb') as file:
    load_model = pickle.load(file)
    

## Using Load_model

In [42]:
load_model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1])